from olympics.components.data_loader import DataLoader
from olympics.components.preprocessor import OlympicPreprocessor
from olympics.components.medal_analyzer import MedalAnalyzer
from olympics.components.trend_analyzer import TrendAnalyzer
from olympics.components.country_analyzer import CountryAnalyzer
from olympics.components.demographic_analyzer import DemographicAnalyzer
